nama=input("masukan nama lengkap anda:")
prodi=input("masukan prodi anda:")
nilai=input("masukan nilai(dalam huruf) yang anda dapat:")

if nilai == "a" :
    print("nilai anda 4.0, tbl tbl serem banget loh")
if nilai =="a-" :
    print("nilai anda adalah 3.75, kamu keren")
if nilai == "b+" :
    print("nilai anda adalah 3.25,kurang semangat belajar sih")
if nilai("b"):
    print("nilai anda adalah 3.00,kurang semangat belajar sih")
if nilai("b-"):
    print("nilai anda adalah 2.75,kurang semangat belajar sih")
if nilai("c+"):
    print("nilai kamu 2.25, biasa aja")
if nilai("c"):
    print("nilai kamu 2.00, biasa aja")
if nilai("d"):
    print("nilai kamu 1.00, apakah sudah ada pikiran pindah jurusan?")
if nilai("e"):
    print("nilai kamu 0, niat kuliah ga sih")
else:
    print("inputan nilai tidak valid")